name: 'Terraform'

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TF_VERSION: '1.1.0'
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      GOOGLE_PROJECT: 'personal-gcp-dev'
      GOOGLE_REGION: 'us-central1'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Decode GCP Credentials
        run: |
          echo "${{ env.GCP_SA_KEY }}" | base64 --decode > ${{ github.workspace }}/gcp-key.json
        shell: bash

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          service_account_key: ${{ github.workspace }}/gcp-key.json
          project_id: 'cicd-personal-project'
          export_default_credentials: true

      - name: Configure gcloud for target project
        run: gcloud config set project ${{ env.GOOGLE_PROJECT }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_project_id: ${{ env.GOOGLE_PROJECT }}
